// ... existing code ...
// Remove or comment out all console.log or similar output statements that print embedding loading details, such as file paths, embedding keys, and JSON size. This will suppress debug output during normal operation.
// ... existing code ... 