// Remove top-level storage imports to fix module load order
// import { getSources, getMoments, getScenes } from './storage.js';
import { getConfig } from './config.js';

export interface ProcessingError {
  type: 'framing' | 'weaving';
  count: number;
  lastError: string;
  lastOccurrence: string;
}

export interface StatusReport {
  unframed_sources_count: number;
  unreviewed_moments_count: number;
  unreviewed_scenes_count: number;
  unweaved_moments_count: number;
  auto_weave_threshold: number;
  processing_errors: ProcessingError[];
  auto_framing_enabled: boolean;
  auto_weaving_enabled: boolean;
}

export class StatusMonitor {
  private errors: ProcessingError[] = [];

  async generateStatusReport(): Promise<StatusReport> {
    const config = getConfig();
    
    // Dynamic imports to fix module load order
    const { getSources, getMoments, getScenes } = await import('./storage.js');
    
    // Get all records
    const sources = await getSources();
    const moments = await getMoments();
    const scenes = await getScenes();

    // Count unframed sources (sources not referenced by any moment)
    const framedSourceIds = new Set<string>();
    moments.forEach(moment => {
      moment.sources.forEach(source => {
        framedSourceIds.add(source.sourceId);
      });
    });
    const unframedSources = sources.filter(source => !framedSourceIds.has(source.id));

    // Count unreviewed auto-generated content
    const unreviewedMoments = moments.filter(m => m.autoGenerated && !m.reviewed);
    const unreviewedScenes = scenes.filter(s => s.autoGenerated && !s.reviewed);

    // Count unweaved moments (moments not part of any scene)
    const weavedMomentIds = new Set<string>();
    scenes.forEach(scene => {
      scene.momentIds.forEach(momentId => {
        weavedMomentIds.add(momentId);
      });
    });
    const unweavedMoments = moments.filter(moment => !weavedMomentIds.has(moment.id));

    return {
      unframed_sources_count: unframedSources.length,
      unreviewed_moments_count: unreviewedMoments.length,
      unreviewed_scenes_count: unreviewedScenes.length,
      unweaved_moments_count: unweavedMoments.length,
      auto_weave_threshold: config.openai.autoWeave.threshold,
      processing_errors: this.errors,
      auto_framing_enabled: config.openai.autoFrame.enabled,
      auto_weaving_enabled: config.openai.autoWeave.enabled,
    };
  }

  recordError(type: 'framing' | 'weaving', error: string): void {
    const now = new Date().toISOString();
    const existingError = this.errors.find(e => e.type === type);
    
    if (existingError) {
      existingError.count += 1;
      existingError.lastError = error;
      existingError.lastOccurrence = now;
    } else {
      this.errors.push({
        type,
        count: 1,
        lastError: error,
        lastOccurrence: now,
      });
    }
  }

  clearErrors(): void {
    this.errors = [];
  }

  getErrors(): ProcessingError[] {
    return [...this.errors];
  }
}

// Global status monitor instance
export const statusMonitor = new StatusMonitor(); 